apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: yadeptrai/search-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_HOST
          value: "movie-db.cohuqu6m26h2.us-east-1.rds.amazonaws.com"
        - name: DATABASE_USER
          value: "admindb"
        - name: DATABASE_NAME
          value: "movie_db"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: contentvideo-secrets
              key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP