apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentvideo-service
  labels:
    app: contentvideo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentvideo-service
  template:
    metadata:
      labels:
        app: contentvideo-service
    spec:
      containers:
      - name: contentvideo-service
        image: yadeptrai/contentvideo-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_HOST
          value: "movie-db.cohuqu6m26h2.us-east-1.rds.amazonaws.com"
        - name: DATABASE_USER
          value: "admindb"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: contentvideo-secrets
              key: DATABASE_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: contentvideo-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: contentvideo-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_MEDIACONVERT_ROLE_ARN
          value: "arn:aws:iam::078287195810:role/service-role/MediaConvert_Default_Role"
---
apiVersion: v1
kind: Service
metadata:
  name: contentvideo-service
spec:
  selector:
    app: contentvideo-service
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP