apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: search-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_USER
          value: "admindb"
        - name: POSTGRES_PASSWORD
          value: "admin123"
        - name: POSTGRES_DB
          value: "movie_db"
        - name: POSTGRES_HOST
          value: "microservices/search-service/create_table.py"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP